# name of your application
APPLICATION = memarray
include ../Makefile.tests_common

USEMODULE += memarray

# Used for invoking _ps_handler
USEMODULE += shell_commands
USEMODULE += ps

include $(RIOTBASE)/Makefile.include
